### ISSUE TITLE
Question about feature request - add exception to some tabs.

### ISSUE THREAD

**Issue by Nillx** [Numynum/NoAutoClose#2]
I love when my tabs are no longer closing when opening different tabs but sometimes there are some tabs that are meant to be closed, like the talk tab that you get when you speak with Katy Stampwhistle [(TOY that lets you use the mailbox)](https://www.wowhead.com/item=156833/katys-stampwhistle)

When you speak with her you get the talk tab and once you click on the "Id like to check my mail" option it auto closes and you see your mail. Right now that doesnt happen and you see both tabs which is a bit ugly. Is it possible to add an exception for that and auto close her tab when you click on the text dialog?
![image](https://user-images.githubusercontent.com/34476875/199724977-5135784e-63d6-4021-bb2e-a49f2573c10b.png)

**Comment by Numynum** [comment]
Hi, I've been thinking about this a bit.. and I don't think I'll do it
I've been playing with this addon in some form for a few years now (only made public recently)
and I've noticed that it's very unpleasant to have some frames ignored

the problem with katy stampwhistle could be fixed by ignoring either the mail frame, or the gossip frame (though it might require ignoring both actually)
especially in dragonflight, that causes weird interactions, when you have a few ignored frames (for example, there was an issue with the spellframe if it was ignored, which meant it'd open and close randomly, which is very annoying)

hope you understand why I'm not planning on adding this in 🙂 (also since having the gossip frame still open isn't a huge deal in this case 🙂)

**Comment by Nillx** [comment]
No problem, its not a huge issue anyway.

**Comment by Numynum** [comment]
after digging a bit more, this should be fixed now, without adding it to the ignore list :)
