### ISSUE TITLE
Renown vendors + AH tab, can we have both open at the same time?

### ISSUE THREAD

**Issue by Nillx** [Numynum/NoAutoClose#5]
Is it possible to let us have the AH tab plus the renwon vendors open at the same time? Ive been trying to buy the mats for the renown rewards but every time i have to close the renown NPC tab and open the AH to buy the item.

Example: Murik the Iskaara Renown vendor in The Azure Span and the longboy AH.

**Comment by Numynum** [comment]
Hi, unfortunately, blizzard limits us to 1 "interaction" active at a time
so the AH UI could stay open for example, but you wouldn't be able to use it to buy the required items
same with the vendor, I could prevent it from closing, but you wouldn't be able to buy anything 

In your specific situation there's probably still value in still seeing the vendor UI, but usually it leads to a bad/unintuitive user experience (since you'd be left with "dead" windows)
I might add a feature toggle for this in the future, but I'm not sure if/when that'd happen ^^

**Comment by Nillx** [comment]
I understand thanks for the explanation.
